//
//  Workspace.swift
//  ENMApp
//
//  Created by Claude on 8/16/25.
//

import ProjectDescription

let workspace = Workspace(
    name: "ENMApp",
    projects: ["Projects/**"],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: true,
        autogeneratedWorkspaceSchemes: .disabled,
        renderMarkdownReadme: false)
)
